# Generated by Django 3.2.12 on 2022-02-15 20:38

import databaseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0002_auto_20220215_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(db_column='user_id', default=databaseapp.models.add_one, primary_key=True, serialize=False)),
                ('age', models.IntegerField(db_column='age')),
                ('email', models.CharField(db_column='email', max_length=45)),
                ('password', models.CharField(db_column='password', max_length=45)),
                ('citizenship', models.CharField(blank=True, db_column='citizenship', max_length=45)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='User_table',
        ),
    ]
