# Generated by Django 3.2.12 on 2022-02-15 21:02

import databaseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseapp', '0003_auto_20220215_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(db_column='country_id', default=databaseapp.models.add_one, primary_key=True, serialize=False)),
                ('country_name', models.CharField(db_column='country_name', max_length=125)),
            ],
            options={
                'db_table': 'Country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Regulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(db_column='country_name', max_length=125)),
                ('regulations', models.TextField(blank=True, db_column='regulations')),
            ],
            options={
                'db_table': 'Regulations',
                'managed': False,
            },
        ),
    ]
